### ISSUE TITLE
Feature Request: Add support for consuming raw kubeconfig

### ISSUE THREAD

**Issue by bmcstdio** [terraform-providers/terraform-provider-kubernetes#530] opened 2019-07-03 16:09 UTC
`config_path` expects the kubeconfig file to exist when `plan`/`apply` run, which may not be the case (such as in Terraform Enterprise, where each run uses a disposable Docker container, so that local files are discarded between runs). I would like to propose that the provider starts accepting a new argument such as `raw_config`, using which one may provide the raw kubeconfig as an input. This can be, for instance, the `kubeconfig` output from the [`terraform-aws-eks`](https://github.com/terraform-aws-modules/terraform-aws-eks) module, which may then be fed (somehow) to `raw_config`. If this sounds like a reasonable feature, I'd be available to work on implementing that.

**Comment by tdmalone** [comment] 2019-07-04 22:10
Possible duplicate of #315

**Comment by paultyng** [comment] 2019-08-05 15:00
This seems like its related to the upstream progressive apply issue: https://github.com/hashicorp/terraform/issues/4149

You cannot currently (reliably) chain together a provider's config with the output of a resource. So you couldn't use the EKS resources to provide information to the Kubernetes provider reliably.

If you would like to extract information from a config file output though you can use `yamldecode`.

**Closed by paultyng** 2019-08-05 15:00 UTC
