### ISSUE TITLE
1.11.+ Fails to initialize correctly when both "username" and "certs" are provided in config

### ISSUE THREAD

**Issue by xp-vit** [terraform-providers/terraform-provider-kubernetes#841] opened 2020-05-07 12:48 UTC
A provider fails to initialize correctly when both "username/password" and "client_certificate/cluster_ca_certificate/client_key" are specified.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version
Terraform v0.12.24                                                                                                     │postgresql_role.cloud_vehicles_service: Destruction complete after 2s
+ provider.azurerm v2.8.0                                                                                              
+ provider.helm v1.2.0                                                                                                 │
+ provider.kubernetes v1.11.1

### Terraform Config
provider "azurerm" {
  version = "~>2.8.0"
  features {}
  subscription_id = var.arm_subscription_id
  client_id = var.arm_client_id
  client_secret = var.arm_client_secret
  tenant_id = var.arm_tenant_id
}

provider "kubernetes" {
  version = "~>1.11.2 "

  host = azurerm_kubernetes_cluster.main.kube_config[0].host

  username = azurerm_kubernetes_cluster.main.kube_config[0].username
  password = azurerm_kubernetes_cluster.main.kube_config[0].password

  client_certificate = base64decode(
  azurerm_kubernetes_cluster.main.kube_config[0].client_certificate,
  )
  client_key = base64decode(
  azurerm_kubernetes_cluster.main.kube_config[0].client_key,
  )
  cluster_ca_certificate = base64decode(
  azurerm_kubernetes_cluster.main.kube_config[0].cluster_ca_certificate,
  )

  insecure = false
}

### Affected Resource(s)
provider

### Expected Behavior
Provider need to be initialized correctly and connect remote Kubernetes cluster or report issue with the config.

### Actual Behavior
Error: Get "http://localhost/api/v1/namespaces/default/secrets/registrypullsecret": dial tcp [::1]:80: connect: connection refused

### Steps to Reproduce
1. Configure Kubernetes provider specifying both "username/password" and "client_certificate/cluster_ca_certificate/client_key"
2. Run `terraform apply`

### Important Factoids
When using provider 1.10.0 the following error is reported:
`Error: Failed to configure: username/password or bearer token may be set, but not both                                   21: provider "kubernetes" { `

Which is correct and provides idea what's wrong and how to fix.

**Comment by dak1n1** [comment] 2020-05-11 23:28
I imagine it's attempting to read the kubeconfig file from the default location. Try adding `load_config_file = false`. Here's an example:

https://github.com/terraform-providers/terraform-provider-kubernetes/pull/840/files#diff-825a498b84b21cd4ff6040ba907e098aR113

There's some info about it here in the docs. https://www.terraform.io/docs/providers/kubernetes/index.html#load_config_file

**Comment by aareet** [comment] 2020-05-20 22:00
Closing since it has been a week since the request for response. If you are able to reproduce, please reopen.

**Closed by aareet** 2020-05-20 22:00 UTC
Labels: bug, waiting-response

**Comment by djsly** [comment] 2020-06-19 06:18
I'm having the same issue 1.10.0, it picks up my configuration from cert/ca/client/secret

with v1.11.3, it only tries to load from ~/kube/config ignoring all the configuration I pass

```
provider "kubernetes" {
  host                   = module.aks.k8s_admin_host
  client_certificate     = base64decode(module.aks.k8s_admin_client_certificate)
  client_key             = base64decode(module.aks.k8s_admin_client_key)
  cluster_ca_certificate = base64decode(module.aks.k8s_admin_cluster_ca_certificate)
}
```
