### ISSUE TITLE
terraform plan dials localhost

### ISSUE THREAD

**Issue by hazcod** [terraform-providers/terraform-provider-kubernetes#758] opened 2020-02-10 11:01 UTC
### Terraform Version
0.12.20

### Affected Resource(s)
- kubernetes_namespace

### Terraform Configuration Files
```hcl
module "scaleway" {
    source                  = "./modules/scaleway"

    scaleway_accesstoken    = var.scaleway_accesstoken
    scaleway_secrettoken    = var.scaleway_secrettoken
    scaleway_organization   = var.scaleway_org
}

module "kubernetes" {
    source                  = "./modules/kubernetes"

    host                    = module.scaleway.kubeconfig[0].host
    token                   = module.scaleway.kubeconfig[0].token
    cluster_ca_certificate  = module.scaleway.kubeconfig[0].cluster_ca_certificate
}
```

### Debug Output
https://github.com/ironPeakServices/infrastructure/runs/435886375?check_suite_focus=true

### Panic Output
```
2020/02/10 10:51:00 [ERROR] module.kubernetes: eval: *terraform.EvalRefresh, err: Get http://localhost/api/v1/namespaces/mainwebsite: dial tcp 127.0.0.1:80: connect: connection refused
```

### Expected Behavior
Dial the APi server url as is indicated in the state file during `terraform plan`.

### Actual Behavior
Dials localhost.

### State excerpt
```json
            "kubeconfig": [
              {
               "host": "https://xxx-59a5-xxx-ad2d-xxx-par.scw.cloud:6443",
                "token": "xxx"
              }
            ],
```

**Comment by nicgrayson** [comment] 2020-02-11 16:24
looks like a dupe of #708

**Comment by sebolabs** [comment] 2020-04-14 20:45
I have a similar issue but with a slightly different configuration where I use the `config_path` property pointing at an ephemeral kubeconfig file:

```hcl
resource "local_file" "kube_config" {
  content  = module.eks_cluster.kube_config
  filename = "/tmp/kubeconfig_${module.eks_cluster.cluster.id}"
}

provider "kubernetes" {
  config_path = local_file.kube_config.filename
}

resource "kubernetes_config_map" "aws_auth" {
  [...]
}
```

If I ran `apply` first and that kubeconfig file got created then running `plan` would pass. However, like I mentioned that config file is ephemeral so it's never there when running `plan`.

Just like the author of this post suggested, I think that a subsequent plan (when the kubeconfig value in the state is present) should somehow use info from the state rather than searching for non-existing things.

**Idea**
In order to avoid expecting that the kubeconfig file exists on the filesystem, in case of usint the `config_path` propety, how about having a `config_content` property instead?

**Comment by aareet** [comment] 2020-06-02 19:51
Closing as a duplicate of #708, please reopen if this is not the case.

**Closed by aareet** 2020-06-02 19:51 UTC
