### ISSUE TITLE
Provider "kubernetes" as of version 1.11.0 says Failed to initialize config: stat /home/vsts/.kube/config (worked fine in 1.10.0)

### ISSUE THREAD

**Issue by MarcelT-NL** [terraform-providers/terraform-provider-kubernetes#768] opened 2020-02-17 21:54 UTC
### Terraform Version
1.11.0

### Affected Resource(s)
Provider "terraform"

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  host  = azurerm_kubernetes_cluster.aks.kube_admin_config.0.host
  client_certificate  = base64decode(azurerm_kubernetes_cluster.aks.kube_admin_config.0.client_certificate)
  client_key  = base64decode(azurerm_kubernetes_cluster.aks.kube_admin_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.aks.kube_admin_config.0.cluster_ca_certificate)
}
```

### Panic Output
Error: Failed to initialize config: stat /home/vsts/.kube/config: no such file or directory

### Expected Behavior
Kubernetes provider should be initialized.

### Actual Behavior
Failed with error above

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
run `terraform plan` on the script above

### Important Factoids
When specifying provider version 1.10.0 everything works ok.
Running in Azure.

**Comment by alexsomesan** [comment] 2020-02-17 22:34
duplicate of #759

**Closed by alexsomesan** 2020-02-17 22:34 UTC
