### ISSUE TITLE
v1.11.0 regression for provider (v1.10 is OK): "...Failed to initialize config: invalid configuration: no configuration has been provided"

### ISSUE THREAD

**Issue by lmgnid** [terraform-providers/terraform-provider-kubernetes#772] opened 2020-02-20 19:56 UTC
Hi there,

Found a regression for the example code bellow: (The same module for the resource "aws_eks_cluster.eks-cluster", so the kubernetes provider is depends on the AWS provider resource)

`
data "aws_eks_cluster_auth" "eks-cluster" {
  name = "${aws_eks_cluster.eks-cluster.name}"
}
provider "kubernetes" {
  host                   = "${aws_eks_cluster.eks-cluster.endpoint}"
  cluster_ca_certificate = "${base64decode(aws_eks_cluster.eks-cluster.certificate_authority.0.data)}"
  token                  = "${data.aws_eks_cluster_auth.eks-cluster.token}"
  load_config_file       = false
  version = "1.11"
  alias = "default"
}

`
This will show the error for "terraform plan":
"...provider.kubernetes: Failed to initialize config: invalid configuration: no configuration has been provided"

But If I only changed the
`
  version = "1.10"
`
The code will work for the same AWS provider version "2.49.0"

PS: I am using the workaround for "provider.default" as in: https://github.com/terraform-providers/terraform-provider-kubernetes/issues/521

### Terraform Version
0.11.14

### Affected Resource(s)
EKS provider 1.11 but NOT 1.10

**Comment by DJAyth** [comment] 2020-02-21 17:39
Just lost 1 hour of my life fighting with this. Many thanks @lmgnid v1.10.0 works great.

**Comment by alexsomesan** [comment] 2020-02-21 18:04
Duplicate of #759 
A WIP solution is available in PR #767 
If you have the possibility to test with custom provider binaries, I'd appreciate confirmation if that solution works for you.

**Closed by alexsomesan** 2020-02-21 18:04 UTC
