### ISSUE TITLE
Feature request:  support the creation of ClusterRole, Role and RoleBinding

### ISSUE THREAD

**Issue by Tapanito** [terraform-providers/terraform-provider-kubernetes#205] opened 2018-11-01 14:42 UTC
This is a request for multiple features.

Terraform already supports ClusterRoleBinding, however it is impossible to define custom ClusterRole, I believe this would be a great addition to the provider.
In addition, defining Role and RoleBinding resources would allow users to create more granular access permissions.

Would it be feasible to introduce these features?

**Comment by mbarrien** [comment] 2018-11-01 20:39
Partial duplicate of #30

**Comment by alexsomesan** [comment] 2019-01-31 15:57
@Sudharma Cluster Role is merged in master (See https://github.com/terraform-providers/terraform-provider-kubernetes/pull/229).
It will be available in the provider release. I don't yet have a fixed date for it, but it should be a matter of weeks.

**Comment by Sudharma** [comment] 2019-01-31 16:04
Great!  I am expecting it for azurerm.

**Comment by alexsomesan** [comment] 2019-02-19 12:48
Released in v1.5.1

**Closed by alexsomesan** 2019-02-19 12:48 UTC
